from typing import Any


class Mlx:
    def mlx_init(self) -> Any: ...
    def mlx_new_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def mlx_new_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def mlx_get_data_addr(self, *args: Any, **kwargs: Any) -> Any: ...
    def mlx_put_image_to_window(self, *args: Any, **kwargs: Any) -> None: ...
    def mlx_destroy_image(self, *args: Any, **kwargs: Any) -> None: ...
    def mlx_clear_window(self, *args: Any, **kwargs: Any) -> None: ...
    def mlx_string_put(self, *args: Any, **kwargs: Any) -> None: ...
    def mlx_loop_exit(self, *args: Any, **kwargs: Any) -> None: ...
    def mlx_key_hook(self, *args: Any, **kwargs: Any) -> Any: ...
    def mlx_hook(self, *args: Any, **kwargs: Any) -> Any: ...
    def mlx_loop(self, *args: Any, **kwargs: Any) -> Any: ...
